# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 398e3295d9b7796a66ff90c080fb140d378aed14441c38968389e53de956f65df3da867caa8ac77c8052084b2a13cc0fe4a3dc9422ff17094da40e761e4cb37d

test:
  secret_key_base: 8c1a8392d4bc9fd1d612c6200da244133a299c8f22e4d6da048945164817d0498790e26174c59073c8d1562b4ca6691998ac0dd731dc3b69560e3480e6405a64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
